Tests ran at _27_Feb_10_13_AM

11 tests passed out of 13 tests.

test_db002.py::test_q1: passed
test_db002.py::test_q2: passed
test_db002.py::test_q3: passed
test_db002.py::test_q4: passed
test_db002.py::test_q5: passed
test_db002.py::test_q6: passed
test_db002.py::test_q7: passed
test_db002.py::test_q8: passed
test_db002.py::test_q9: passed
test_db002.py::test_q10: passed
test_db002.py::test_q11: failed
test_db002.py::test_q12: failed
test_db002.py::test_q13: passed
