Tests ran at 02 Mar 11 33 AM

0 tests passed out of 12 tests.

test_db006.py::test_q1: failed
test_db006.py::test_q2: failed
test_db006.py::test_q3: failed
test_db006.py::test_q4: failed
test_db006.py::test_q5: failed
test_db006.py::test_q6: failed
test_db006.py::test_q7: failed
test_db006.py::test_q8: failed
test_db006.py::test_q9: failed
test_db006.py::test_q10: failed
test_db006.py::test_q11: failed
test_db006.py::test_q12: failed
